from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 397)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 81))
        self.label.setStyleSheet("background-color: rgb(231, 229, 255);")
        self.label.setObjectName("label")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(0, 320, 130, 81))
        self.btn0.setObjectName("btn0")
        self.btneq = QtWidgets.QPushButton(self.centralwidget)
        self.btneq.setGeometry(QtCore.QRect(120, 320, 126, 81))
        self.btneq.setObjectName("btneq")
        self.btnpl = QtWidgets.QPushButton(self.centralwidget)
        self.btnpl.setGeometry(QtCore.QRect(245, 80, 51, 81))
        self.btnpl.setObjectName("btnpl")
        self.btnmin = QtWidgets.QPushButton(self.centralwidget)
        self.btnmin.setGeometry(QtCore.QRect(245, 240, 51, 81))
        self.btnmin.setObjectName("btnmin")
        self.btndiv = QtWidgets.QPushButton(self.centralwidget)
        self.btndiv.setGeometry(QtCore.QRect(245, 320, 51, 81))
        self.btndiv.setObjectName("btndiv")
        self.btnmul = QtWidgets.QPushButton(self.centralwidget)
        self.btnmul.setGeometry(QtCore.QRect(245, 160, 51, 81))
        self.btnmul.setObjectName("btnmul")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 80, 86, 81))
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(80, 80, 86, 81))
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(160, 80, 86, 81))
        self.btn9.setObjectName("btn9")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 160, 86, 81))
        self.btn4.setObjectName("btn4")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 240, 86, 81))
        self.btn1.setObjectName("btn1")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(80, 160, 86, 81))
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(160, 160, 86, 81))
        self.btn6.setObjectName("btn6")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(80, 240, 86, 81))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(160, 240, 86, 81))
        self.btn3.setObjectName("btn3")
        self.label.raise_()
        self.btn0.raise_()
        self.btnpl.raise_()
        self.btnmin.raise_()
        self.btndiv.raise_()
        self.btnmul.raise_()
        self.btn7.raise_()
        self.btn8.raise_()
        self.btn9.raise_()
        self.btn4.raise_()
        self.btn1.raise_()
        self.btn5.raise_()
        self.btn6.raise_()
        self.btn2.raise_()
        self.btn3.raise_()
        self.btneq.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calc"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btneq.setText(_translate("MainWindow", "="))
        self.btnpl.setText(_translate("MainWindow", "+"))
        self.btnmin.setText(_translate("MainWindow", "-"))
        self.btndiv.setText(_translate("MainWindow", "/"))
        self.btnmul.setText(_translate("MainWindow", "*"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))

    def add_functions(self):
        self.btn0.clicked.connect(lambda: self.write_number(self.btn0.text()))
        self.btn1.clicked.connect(lambda: self.write_number(self.btn1.text()))
        self.btn2.clicked.connect(lambda: self.write_number(self.btn2.text()))
        self.btn3.clicked.connect(lambda: self.write_number(self.btn3.text()))
        self.btn4.clicked.connect(lambda: self.write_number(self.btn4.text()))
        self.btn5.clicked.connect(lambda: self.write_number(self.btn5.text()))
        self.btn6.clicked.connect(lambda: self.write_number(self.btn6.text()))
        self.btn7.clicked.connect(lambda: self.write_number(self.btn7.text()))
        self.btn8.clicked.connect(lambda: self.write_number(self.btn8.text()))
        self.btn9.clicked.connect(lambda: self.write_number(self.btn9.text()))
        self.btnpl.clicked.connect(lambda: self.write_number(self.btnpl.text()))
        self.btnmin.clicked.connect(lambda: self.write_number(self.btnmin.text()))
        self.btnmul.clicked.connect(lambda: self.write_number(self.btnmul.text()))
        self.btndiv.clicked.connect(lambda: self.write_number(self.btn0.text()))

        self.btneq.clicked.connect(self.results)

    def write_number(self, number):
        if self.label.text() == '0':
            self.label.setText(number)
        else:
            self.label.setText(self.label.text() + number)


    def results(self):
        try:
            res = eval(self.label.text())
            self.label.setText(str(res))
        except:
            error = QMessageBox()
            error.setWindowTitle('Error')
            error.setText('Error')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok)
            error.exec_()

            res = 0
            self.label.setText(str(res))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
